### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by toplenboren** [pahaz/pahaz.8iq.dev#1]
curl `https://pahaz.8iq.dev` not working, is the server up yet?

**Comment by pahaz** [comment]
It's online! Welcome! `curl -v https://pahaz.8iq.dev --output /dev/null`

<img width="687" alt="image" src="https://github.com/pahaz/pahaz.8iq.dev/assets/1394025/a17455c2-c240-4580-ad9b-59a1399f1b5f">

**Comment by toplenboren** [comment]
Yes! It's online now. Closing the issue
